### ISSUE TITLE
Bug: Unable to update profile; information disappears

### ISSUE THREAD

**Issue by jonton11** [networksforchange/teamMemberApp#1]
1. Before:

<img width="1440" alt="Screen Shot 2019-12-05 at 7 12 28 PM" src="https://user-images.githubusercontent.com/10856948/70292681-a9863e00-1793-11ea-9200-42f395dd9dc1.png">

2. Clicked 'Update'

3. After
<img width="1439" alt="Screen Shot 2019-12-05 at 7 12 38 PM" src="https://user-images.githubusercontent.com/10856948/70292682-aa1ed480-1793-11ea-8578-bf9f2f8dd25c.png">

**Comment by MikeYuanMY** [comment]
issue identified, corrected account method
